language: node_js
node_js:
  - node
addons:
  chrome: stable
before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
before_script:
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin
deploy:
  provider: firebase
  token: 1//0h9oFNMjlb4-JCgYIARAAGBESNwF-L9IrHOy1ZiDkbs2T4_LUQEc4av2bKTNwJCaayfG0z_8ppJPjVYBnMN7i1jV_z2XvN6xx2fE
